# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- develop

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerfilePath: '**/WebSiteDockerfile'

stages:
- stage: Build
  displayName: Build
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: build
        dockerfile: $(dockerfilePath)
        tags: |
          $(tag)

    - task: ECRPushImage@1
      inputs:
        awsCredentials: 'AwsContainer'
        regionName: 'eu-west-1'
        imageSource: 'imagename'
        sourceImageName: 'StuffPackerWebSiteTest'
        repositoryName: 'StuffPackerWebSiteTest'
        autoCreateRepository: true
        forceDockerNamingConventions: true