version: '3.8'

services:  
  mssql:
    image: mcr.microsoft.com/azure-sql-edge-developer
    restart: always
    ports:
      - "41433:1433"
    environment:
      SA_PASSWORD: "8yNMaSUTtiNNVNvS"
      ACCEPT_EULA: "Y"
  mongodb:
    image: mongo
    container_name: StuffPackerDev
    hostname: azurite
    restart: always
    ports:
      - "41017:27017"

 